# Default values for gocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
server:
  name: 'gocd-server'
  replicaCount: 1
  image:
    repository: gocd/gocd-server
    tag: v17.10.0
    pullPolicy: IfNotPresent
  service:
    name: gocd-server-service
    type: NodePort
    httpPort: 8153
    httpsPort: 8154
    nodeHttpPort: 30000
    nodeHttpsPort: 30001
  ingress:
    enabled: true
  # Used to create an Ingress record.
    hosts:
      - foo.go.cd
    annotations:
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
    tls:
agent:
  replicaCount: 1
  name: 'gocd-agent'
  image:
    repository: gocd/gocd-agent-alpine-3.6
    tag: v17.10.0
    pullPolicy: IfNotPresent
  goServerUrl:
  agentAutoRegisterKey:
  agentAutoRegisterResources:
  agentAutoRegisterEnvironemnts:
  agentAutoRegisterHostname:

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
