apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
  labels:
    app: {{ template "name" . }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        role: server
    spec:
      volumes:
        - name: godata-vol
          persistentVolumeClaim:
            claimName: {{ .Values.server.persistence.name }}
      containers:
        - name: {{ .Values.server.name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - containerPort: 8153
            - containerPort: 8154
          volumeMounts:
          - name: godata-vol
            mountPath: /godata
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
