apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}-deployment
  labels:
    app: {{ .Values.server.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    role: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        role: server
    spec:
      containers:
        - name: {{ .Values.server.name}}
          image: "{{ .Values.server.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - containerPort: 8153
            - containerPort: 8154

          resources:
{{ toYaml .Values.server.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
    {{- end }}
