{{- if .Values.server.ingress.enabled -}}
{{- $serviceName := .Values.server.service.name -}}
{{- $serviceHttpPort := .Values.server.service.httpPort -}}
{{- $serviceHttpsPort := .Values.server.service.httpsPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ .Values.server.service.httpPort }}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $serviceHttpPort }}
  {{- end -}}
{{- end -}}
