{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.server.persistence.name }}
  labels:
    app: {{ .Values.server.name }}
    role: server
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | quote }}
{{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
{{- else }}
  storageClassName: ""
{{- end }}
  selector:
    matchLabels:
      app: "gocd-server"
{{- end }}
