apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.service.name }}
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.httpPort }}
      targetPort: 8153
      nodePort: {{ .Values.server.service.nodeHttpPort }}
      protocol: TCP
      name: http

    - port: {{ .Values.server.service.httpsPort }}
      targetPort: 8154
      nodePort: {{ .Values.server.service.nodeHttpsPort }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "name" . }}
    role: server
